export type Proposal = {
  id: string;
  team: string;
  idea: string;
  plan: string;
  deadline: string;
  link: string;
  status: "pending" | "accepted" | "rejected";
};

// Unknown text fields are stored as "Не указано".
export type TaskCard = {
  id: string;
  title: string;
  topic: string;
  context: string;
  need: string;
  users: string;
  data: string;
  constraints: string;
  expectedResult: string;
  successCriteria: string;
  contact: string;
  interactionFormat: string;
  // Calculated by calculateScore(card).total, never generated by AI.
  score: number;
  status: "draft" | "published" | "in_progress";
  proposals: Proposal[];
};
